# e.g. condor_submit year=2024 submit_analysis.sub
executable     = run_analysis.sh
arguments      = $(ClusterId) $(ProcId) $(year) $(era)
output         = logs/analysis.$(era).s0.$(ClusterId).$(ProcId).out
error          = logs/analysis.$(era).s0.$(ClusterId).$(ProcId).err
log            = logs/analysis.log
request_cpus   = 4
request_memory = 64GB

# eras_2024      = C D E F G H I
eras_2023      = B C D
eras_2024      = C D E F G H I I-v2 I-v3
eras_2025      = B C-v1 C-v2 D E F-v1 F-v2 G

queue era in $(eras_$(year))