crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream0_Mini_v4
crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream1_Mini_v4
crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream2_Mini_v4
crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream3_Mini_v4
crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream4_Mini_v4
crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream5_Mini_v4
crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream6_Mini_v4
crab report -d crab_projects/crab_SkimDsPhiPi_YEAReraERANAME_stream7_Mini_v4
